spring.application.name=backend

#mysql configuration
spring.datasource.url=jdbc:mysql://localhost:3307/task_scheduler
spring.datasource.username=root
spring.datasource.password=S@kshi$root99

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080

jwt.secret=ZmY4YzQzYTIzOGQ3ZjM0Zjc5OTBiOTFiNTRmMjM5ZjIwOTBkM2QwYmYwNmI0Nzk3M2NlZmY4NmY2Y2E0YzRmMg==
jwt.expiration=86400000